### ISSUE TITLE
Redirect is not working

### ISSUE THREAD

**Issue by angoca** [OSMLatam/state#1]
Esto es lo que me arroja
<img width="592" alt="image" src="https://github.com/user-attachments/assets/a0eb7f05-1bde-42f3-a410-f46e0e8e3287">

**Comment by vgeorge** [comment]
@risturiz alguna idea de lo que pueda estar pasando?

**Comment by risturiz** [comment]
Hola @vgeorge, pues dentro de Cloudflare no existe ese registro... Hacia donde debería apuntar? 

No sé si lo están confundiendo con https://2024.osmlatam.org/

**Comment by vgeorge** [comment]
@angoca podrías intentar acceder nuevamente? Está a funcionar para mí.

**Comment by angoca** [comment]
Hola Vitor, ya sirve el redireccionamiento a la página principal. Gracias.
